Update .env.example
Change space to underscore. Space cause an error fatal at php artisan optimize step of composer install.
Fatal error: Uncaught ReflectionException: Class log does not exist in C:\xampp\htdocs\DEV-TV\vendor\laravel\framework\src\Illuminate\Container\Container.php:734
That fix it.